platform :ios, '12.0'

target 'SwiftTemplate' do

  use_frameworks!

  pod 'Alamofire'
  pod 'RxSwift', '~> 4.5.0'
  pod 'RxCocoa', '~> 4.5.0'
  pod 'MBProgressHUD'

  target 'SwiftTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
